import React, { createContext, useState, useContext, useEffect } from 'react';
 
const LanguageContext = createContext();
 
export const useLanguage = () => {
  return useContext(LanguageContext);
};
 
export const LanguageProvider = ({ children }) => {
  const [languageText, setLanguageText] = useState({
    english: {
      theme: 'Theme',
      syncData: 'Sync Data',
      fontSize: 'Font Size',
      selectLanguage: 'Select Language',
      profiledata : 'Profile Data',
      showGDPRContent : 'Show GDPR Content',
      GDPRContentHere : 'GDPR Content Here...',
      close : 'Close',
      homeLabel: 'Home',
      mapLabel : 'Map',
      profileLabel : 'Profile',
      settingsLabel : 'Settings',
      payments:'Payments',
      calendarLabel:'Events',
      messages:'Messages',
      startNavigation : 'Start Navigation',
      currentlocation : 'Current Location',
      destination : 'Destination',
      source : 'Source',
      searchdata : 'Search Data',
      email:'Email',
      password:'Password',
      forgotPassword:'Forgot Password or Login with OTP',
      login:'Login',
      signUp:'Sign Up',
      noAccount:'Don`t have an account?',
      firstName:'First Name',
      lastName:'Last Name',
      emailAddress: 'Email Id',
      contactNumber:'Phone Number',
      countryCode:'Country Code',
      submit:'Submit',
      forgotPasswordScreen:'ForgotPassword',
      resetPassword:'ResetPassword',
      oTPVerification:'OTPVerification',
      googleSignOut:'GoogleSignOut',
      signOut:'Sign Out',
      emailOrPhno:'Email/PhoneNumber',
      emailOTP:'enter the Code',
      newPassword:'enter the New Password',
      confirmPassword:'enter the Confirm Password',
      phoneOtp:'Enter the OTP (6 digits)',
      enterFontSize:'Enter Font Size',
      validationError:'Validation Error',
      allFieldsRequired:'All Fields are Required',
      invalidEmail:'Invalid Email Address',
      invalidPassword:'Invalid Password Format',
      phnoValidation:'Contact Number must be exactly 10 digits',
      invalidEmailOrPhno:'Invalid Email Address or Phone Number',
      otpValidation:'OTP should be exactly 6 digits',
      newAndConfirmPasswordSame:'New Password && Confirm Password must be same',
      syncSuccess:'Sync Successful',
      syncDataSucees:'Data has been synchronized',
      noChange:'No Changes',
      alreadySync:'Data is already up to date',
      locationDenied:'Location permission denied',
      invalidInput:'Invalid Input',
      sourceAndDestinationAlert:'Please select  source and destination.',
      sourceAlert:'Please select  source.',
      destinationAlert:'Please select  destination.',
      sourceDestinationSameAlert:'Can`t apply same route options.Try again',
      cancel:'Cancel',
      editProfile:'Edit Profile',
      saveProfile:'Save Profile',
      makepayment:'Make Payment',
      amount:'Amount',
      name:'Name',
      contact:'Contact',
      plinkId:'PlinkId',
      enterAmount:'Enter Amount',
      enterName:'Enter Name',
      enterValidContact:'Enter Valid Contact Number',
      enterEmail:'Enter Valid Email',
      enterPlinkid:'Enter Any 3 numbers',
      amountgretter100:'Amount should be > 100 ',
      selectDateValidation:'Please Select Date',
      SelectedDate:'Selected Date',
      eventDetails:'Event Details',
      deleteEvent:'Delete Event',
      invalidTime:'Invalid Time',
      eventCreatedAlert:'Event Created Successfully',
      eventDeletedAlert:'Event Deleted Successfully',
      enterEventName:'Enter Event Name',
      enterLocation:'Enter Location',
      enterTime:'Enter Time',
      createEvent:'Create Event',
      enterId:'Enter Id',
      image:'Image',
      video:'Video',
      share:'Share',
      chooseImage:'Choose Image',
      openCamera:'Open Camera',
      chooseVideo:'Choose Video',
      recordVideo:'Record Video',
      enterFeedback:'Enter your feedback here...',
      poor:'Poor',
      bad:'Bad',
      ok: 'OK', 
      good:'Good',
      excellent: 'Excellent',
      reactnativeratings:'ReactNativeRatings',
      rated:'Rated',
      feedbackalert:'Thank you for your feedback! You rated',
      feedback:'Feedback',
      ratingalert:'Rating cannot be zero and feedback cannot be empty.',
      pickDocument:'Pick Document',
      upload:'Upload',
      externalService:'ExternalService',
      music:'Music',
      pickAudio:'Pick Audio',
      play:'Play',
      pause:'Pause',
      type:'Type',
      size:'Size',

      //getting eventdetails
      id:'Id',
      name:'Event Name',
      location:'Location',
      date:'Date',
      time:'Time',
      createdBy:'Created By',
      status:'Status',

    },
    german: {
      theme: 'Thema',
      syncData: 'Daten synchronisieren',
      fontSize: 'Schriftgröße',
      selectLanguage: 'Sprache auswählen',
      profiledata:'Profildaten',
      showGDPRContent : 'DSGVO-Inhalte anzeigen',
      GDPRContentHere : 'DSGVO-Inhalt hier...',
      close : 'Schließen',
      homeLabel: 'Heim',
      mapLabel : 'Karte',
      profileLabel : 'Profil',
      settingsLabel : 'Einstellungen',
      payments:'Zahlungen',
      calendarLabel:'Ereignisse',
      messages:'Mitteilungen',
      startNavigation : 'Beginnen Sie mit dem Stöbern',
      currentlocation : 'Aktueller Standort',
      destination : 'Ziel',
      source : 'Quelle',
      searchdata : 'Daten durchsuchen',
      email:'Email',
      password:'Passwort',
      forgotPassword:'Passwort vergessen oder mit OTP anmelden',
      login:'Anmeldung',
      signUp:'Melden Sie sich an',
      noAccount:'Sie haben noch kein Konto?',
      firstName:'Vorname',
      lastName:'Familienname, Nachname',
      emailAddress: 'E-Mail-ID',
      contactNumber:'Telefonnummer',
      countryCode:'Landesvorwahl',
      submit:'Einreichen',
      forgotPasswordScreen:'Passwort vergessen',
      resetPassword:'Passwort zurücksetzen',
      oTPVerification:'OTP-Verifizierung',
      googleSignOut:'GoogleSignOut',
      signOut:'Abmelden',
      emailOrPhno:'E-Mail/Telefonnummer',
      emailOTP:'Code eingeben',
      newPassword:'Geben Sie das neue Passwort ein',
      confirmPassword:'Geben Sie das Bestätigungskennwort ein',
      phoneOtp:'Geben Sie das OTP ein (6 Ziffern)',
      enterFontSize:'Geben Sie die Schriftgröße ein',
      validationError:'Validierungsfehler',
      allFieldsRequired:'Alle Felder sind erforderlich',
      invalidEmail:'Ungültige E-Mail-Adresse',
      invalidPassword:'Ungültiges Kennwort Format',
      phnoValidation:'Die Kontaktnummer muss genau 10 Ziffern lang sein',
      invalidEmailOrPhno:'Ungültige E-Mail-Adresse oder Telefonnummer',
      otpValidation:'OTP sollte genau 6 Ziffern haben',
      newAndConfirmPasswordSame:'Neues Passwort und Passwort bestätigen müssen identisch sein',
      syncSuccess:'Synchronisierung erfolgreich',
      syncDataSucees:'Die Daten wurden synchronisiert',
      noChange:'Keine Änderungen',
      alreadySync:'Die Daten sind bereits aktuell',
      locationDenied:'Standortberechtigung verweigert',
      invalidInput:'Ungültige Eingabe',
      sourceAndDestinationAlert:'Bitte wählen Sie Quelle und Ziel aus.',
      sourceAlert:'Bitte wählen Sie die Quelle aus.',
      destinationAlert:'Bitte Ziel auswählen.',
      sourceDestinationSameAlert:'Dieselben Routenoptionen können nicht angewendet werden. Versuchen Sie es erneut',
      cancel:'Stornieren',
      editProfile:'Profil bearbeiten',
      saveProfile:'Profil sichern',
      makepayment:'Zahlung leisten',
      amount:'Menge',
      name:'Name',
      contact:'Kontakt',
      plinkId:'PlinkId',
      enterAmount:'Menge eingeben',
      enterName:'Name eingeben',
      enterValidContact:'Geben Sie einen gültigen Kontakt ein',
      enterEmail:'Email eingeben',
      enterPlinkid:'Geben Sie 3 beliebige Zahlen ein',
      amountgretter100:'Der Betrag sollte > 100 sein',
      selectDateValidation:'Bitte wählen Sie ein Datum',
      SelectedDate:'Ausgewähltes Datum',
      eventDetails:'Details zur Veranstaltung',
      deleteEvent:'Ereignis löschen',
      invalidTime:'Ungültige Uhrzeit',
      eventCreatedAlert:'Ereignis erfolgreich erstellt',
      eventDeletedAlert:'Ereignis erfolgreich gelöscht',
      enterEventName:'Ereignisnamen eingeben',
      enterLocation:'Standort eingeben',
      enterTime:'Zeit eingeben',
      createEvent:'Ereignis erstellen',
      enterId:'ID eingeben',
      image:'Bild',
      video:'Video',
      share:'Aktie',
      chooseImage:'Wählen Sie Bild',
      openCamera:'Öffnen Sie die Kamera',
      chooseVideo:'Wählen Sie Video',
      recordVideo:'Ein Video aufnehmen',
      enterFeedback:'Geben Sie hier Ihr Feedback ein...',
      poor:'Arm',
      bad:'Schlecht',
      ok: 'OK', 
      good:'Gut',
      excellent: 'Exzellent',
      reactnativeratings:'ReactNativeRatings',
      rated:'Bewertet',
      feedbackalert:'Danke für Ihre Rückmeldung! Du hast bewertet',
      feedback:'Rückmeldung',
      ratingalert:'Die Bewertung darf nicht Null sein und das Feedback darf nicht leer sein.',
      pickDocument:'Wählen Sie Dokument aus',
      upload:'Hochladen',
      externalService:'ExternalService',
      music:'Musik',
      pickAudio:'Wählen Sie „Audio“',
      play:'Spielen',
      pause:'Pause',
      type:'Typ',
      size:'Größe',

      //getting eventdetails
      id:'Id',
      name:'Name',
      location:'Ort',
      date:'Datum',
      time:'Zeit',
      createdBy:'Erstellt von',
      status:'Status'


    },
    chinese: {
      theme: '主题',
      syncData: '同步數據',
      fontSize: '字体大小',
      selectLanguage: '选择语言',
      profiledata:'资料数据 ',
      showGDPRContent : '显示 般資料保護條例 内容',
      GDPRContentHere : '一般資料保護條例 內容在此...',
      close : '關閉',
      homeLabel: '家',
      mapLabel : '地圖',
      profileLabel : '輪廓',
      settingsLabel : '設定',
      payments:'付款方式',
      calendarLabel:'事件',
      messages:'留言',
      startNavigation : '開始導航',
      currentlocation : '目前位置',
      destination : '目的地',
      source : '来源',
      searchdata : '搜尋數據',
      email:'電子郵件',
      password:'密碼',
      forgotPassword:'忘記密碼或使用 OTP 登入',
      login:'登入',
      signUp:'報名',
      noAccount:'沒有帳戶？',
      firstName:'名',
      lastName:'姓',
      emailAddress: '電子郵件ID',
      contactNumber:'電話號碼',
      countryCode:'國家代碼',
      submit:'提交',
      forgotPasswordScreen:'忘記密碼',
      resetPassword:'重新設密碼',
      oTPVerification:'OTP驗證',
      googleSignOut:'谷歌退出',
      signOut:'登出',
      emailOrPhno:'電子郵件/電話號碼',
      emailOTP:'輸入代碼',
      newPassword:'輸入新密碼',
      confirmPassword:'輸入確認密碼',
      phoneOtp:'輸入 OTP（6 位數）',
      enterFontSize:'輸入字體大小',
      validationError:'驗證錯誤',
      allFieldsRequired:'各個領域都需要',
      invalidEmail:'無效的郵件地址',
      invalidPassword:'無效的密碼格式',
      phnoValidation:'聯絡電話必須剛好是 10 位數字',
      invalidEmailOrPhno:'電子郵件地址或電話號碼無效',
      otpValidation:'OTP 應該剛好是 6 位數字',
      newAndConfirmPasswordSame:'新密碼和確認密碼必須相同',
      syncSuccess:'同步成功',
      syncDataSucees:'資料已同步',
      noChange:'沒有變化',
      alreadySync:'數據已經是最新的',
      locationDenied:'位置權限被拒絕',
      invalidInput:'輸入無效',
      sourceAndDestinationAlert:'請選擇來源和目的地。',
      sourceAlert:'請選擇來源。',
      destinationAlert:'請選擇目的地。',
      sourceDestinationSameAlert:'無法套用相同的路線選項。請重試',
      cancel:'取消',
      editProfile:'編輯個人資料',
      saveProfile:'儲存個人資訊',
      makepayment:'付款',
      amount:'數量',
      name:'姓名',
      contact:'接觸',
      plinkId:'PlinkId的',
      enterAmount:'輸入金額',
      enterName:'輸入名字',
      enterValidContact:'輸入有效聯絡方式',
      enterEmail:'輸入電子郵件',
      enterPlinkid:'輸入任3個數字',
      amountgretter100:'金額應> 100',
      selectDateValidation:'請選擇日期',
      SelectedDate:'選取日期',
      eventDetails:'活動詳情',
      deleteEvent:'刪除事件',
      invalidTime:'無效時間',
      eventCreatedAlert:'事件創建成功',
      eventDeletedAlert:'事件已成功刪除',
      enterEventName:'輸入事件名稱',
      enterLocation:'輸入位置',
      enterTime:'輸入時間',
      createEvent:'創建事件',
      enterId:'輸入ID',
      image:'影像',
      video:'影片',
      share:'分享',
      chooseImage:'選擇圖片',
      openCamera:'開放式攝影機',
      chooseVideo:'選擇影片',
      recordVideo:'錄影影片',
      enterFeedback:'在此輸入您的回饋...',
      poor:'貧窮的',
      bad:'壞的',
      ok: '好的', 
      good:'好的',
      excellent: '出色的',
      reactnativeratings:'ReactNative 評級',
      rated:'額定',
      feedbackalert:'感謝您的回饋意見！您評價',
      feedback:'回饋',
      ratingalert:'評分不能為零，回饋不能為空。',
      pickDocument:'選擇文件',
      upload:'上傳',
      externalService:'外部服務',
      music:'音樂',
      pickAudio:'選擇音訊',
      play:'玩',
      pause:'暫停',
      type:'類型',
      size:'尺寸',


      //getting eventdetails
      id:'同上',
      name:'名字',
      location:'位置',
      date:'日期',
      time:'時間',
      createdBy:'建立者',
      status:'地位'

    },
  });
 
  const [selectedLanguage, setSelectedLanguage] = useState('english');
 
  const changeLanguage = (language) => {
    setSelectedLanguage(language);
  };
 
  const getTextForSelectedLanguage = (textKey) => {
    return languageText[selectedLanguage][textKey];
  };
 
 
 
  useEffect(() => {
  }, [selectedLanguage]);
 
  return (
    <LanguageContext.Provider
      value={{
        selectedLanguage,
        changeLanguage,
        getTextForSelectedLanguage,
      }}
    >
      {children}
    </LanguageContext.Provider>
  );
};
 
export default LanguageContext;
 